import type { GoalTemplate, NicheId } from '@/lib/types'

/**
 * Mecanismo F — Plantillas pre-armadas por tipo de meta.
 *
 * Cada plantilla trae hitos típicos, un pool de acciones cortas y concretas
 * para el plan del día, y la frecuencia con la que la meta pide acción.
 * El usuario ajusta detalles; no inventa la estructura desde cero.
 */
export const TEMPLATES: GoalTemplate[] = [
  {
    key: 'salud_fisico',
    label: 'Mejorar mi físico / salud',
    emoji: '💪',
    defaultArea: 'salud',
    description: 'Bajar de peso, ganar músculo, correr tu primera carrera o crear un hábito de movimiento sostenible.',
    keywords: [
      'peso', 'adelgazar', 'bajar', 'kilos', 'gym', 'gimnasio', 'correr', 'caminar',
      'ejercicio', 'salud', 'físico', 'fisico', 'musculo', 'músculo', 'entrenar',
      'fuerza', 'cardio', 'dieta', 'comer', 'maratón', 'maraton', 'running', 'trotar',
      'pesas', 'yoga', 'pilates', 'nadar', 'natación', 'natacion', 'bici', 'bicicleta',
      'deporte', 'tonificar', 'abdominales', 'crossfit', 'spinning', 'flexiones',
      'nutricion', 'nutrición', 'alimentacion', 'alimentación', 'proteína', 'proteina',
      'calorias', 'calorías', 'hipertrofia', 'resistencia', 'flexibilidad', 'trote',
      'triatlón', 'triatlon', 'ciclismo', 'senderismo', 'boxeo', 'artes marciales',
      'zumba', 'baile', 'hiit', 'funcional',
    ],
    milestones: [
      'Medir tu punto de partida: anota peso, medidas o el tiempo que aguantas corriendo hoy',
      'Completar 2 semanas seguidas con al menos 3 sesiones de ejercicio por semana',
      'Notar un cambio objetivo: más resistencia, menos medidas o mejor estado de ánimo',
      'Alcanzar tu primer resultado concreto (−3 kg, correr 5 km sin parar, etc.)',
      'Mantener el hábito por 60 días sin necesitar motivación externa',
    ],
    actions: [
      'Completar tu sesión de entrenamiento de hoy (aunque sean 20 min)',
      'Preparar una comida saludable desde cero y anotar los ingredientes',
      'Hacer una caminata de 30 min a paso vivo sin usar el teléfono',
      'Registrar lo que comiste hoy en un bloc o app y evaluar cómo estuvo',
      'Hacer 15 min de estiramientos o movilidad articular al levantarte',
      'Completar un circuito de fuerza en casa: sentadillas, flexiones y plancha',
      'Beber 2 litros de agua durante el día y tachar cada vaso completado',
    ],
    kickoffActions: [
      'Anota tu peso, medidas o marca de referencia de hoy para tener un punto de partida',
      'Elige 3 días fijos de la semana para entrenar y ponlos en tu calendario',
      'Deja la ropa de ejercicio y la botella de agua preparadas para mañana por la noche',
      'Haz una primera sesión corta de 20 min para romper la inercia',
      'Busca una rutina de principiante adecuada a tu nivel y guarda el enlace',
    ],
    cadence: 'weekdays',
    reviewEveryDays: 7,
  },
  {
    key: 'aprender_habilidad',
    label: 'Aprender una habilidad',
    emoji: '📚',
    defaultArea: 'aprendizaje',
    description: 'Dominar un idioma, aprender a programar, tocar un instrumento o cualquier habilidad nueva desde cero.',
    keywords: [
      'aprender', 'idioma', 'idiomas', 'inglés', 'ingles', 'francés', 'frances',
      'alemán', 'aleman', 'italiano', 'portugués', 'portugues', 'japonés', 'japones',
      'chino', 'programar', 'código', 'codigo', 'python', 'javascript', 'excel',
      'curso', 'estudiar', 'instrumento', 'guitarra', 'piano', 'batería', 'bateria',
      'habilidad', 'tocar', 'dibujar', 'fotografía', 'fotografia', 'cocinar', 'bailar',
      'cantar', 'skill', 'diseño', 'diseno', 'disenar', 'diseñar', 'illustrator',
      'photoshop', 'edicion', 'edición', 'video', 'podcast', 'oratoria', 'escritura',
      'redaccion', 'redacción', 'negociacion', 'negociación', 'liderazgo', 'react',
      'typescript', 'java', 'swift', 'kotlin', 'sql', 'data', 'machine learning',
      'ukulele', 'violin', 'violín', 'trompeta', 'saxofón', 'saxofon',
      'acuarela', 'pintura', 'escultura', 'ceramica', 'cerámica', 'costura',
      'tejido', 'knitting', 'pastelería', 'pasteleria', 'repostería', 'reposteria',
    ],
    milestones: [
      'Elegir UN recurso principal (curso, libro o app) y completar la primera lección',
      'Terminar el módulo introductorio y practicar con tu primer ejercicio real',
      'Alcanzar el nivel básico: hacer algo sencillo sin consultar notas',
      'Completar un proyecto o prueba real que demuestre lo que aprendiste',
      'Llegar al nivel donde ya puedes usar la habilidad en situaciones cotidianas',
    ],
    actions: [
      'Estudiar 25 min con el método Pomodoro: una sola cosa, sin distracciones',
      'Repasar los conceptos de ayer haciendo un resumen de una página',
      'Completar la siguiente lección o capítulo de tu recurso principal',
      'Resolver 3 ejercicios o problemas de práctica y revisar tus errores',
      'Aplicar lo aprendido en un mini proyecto real aunque sea de 10 minutos',
      'Anotar 5 conceptos nuevos con tus propias palabras y un ejemplo',
      'Buscar un video o artículo complementario sobre el punto que menos entiendes',
    ],
    kickoffActions: [
      'Elige UN curso, libro o app y haz la primera lección ahora mismo',
      'Define cuántas horas por semana le vas a dedicar y bloquéalas en tu agenda',
      'Prepara tu espacio de aprendizaje: silencio, agua, bloc de notas y timer',
      'Haz la primera lección completa sin saltar partes',
      'Anota tu punto de partida: qué sabes ya y qué quieres lograr en 30 días',
    ],
    cadence: 'weekdays',
    reviewEveryDays: 7,
  },
  {
    key: 'finanzas',
    label: 'Ahorrar / mejorar finanzas',
    emoji: '💰',
    defaultArea: 'finanzas',
    description: 'Ahorrar para un objetivo concreto, salir de deudas o construir un fondo de emergencia.',
    keywords: [
      'ahorrar', 'ahorro', 'dinero', 'plata', 'finanzas', 'deuda', 'deudas', 'gastos',
      'presupuesto', 'invertir', 'inversión', 'inversion', 'bolsa', 'cripto', 'bitcoin',
      'jubilación', 'jubilacion', 'tarjeta', 'crédito', 'credito', 'económico',
      'economico', 'ingresos', 'fondo', 'ethereum', 'criptomonedas', 'acciones',
      'fondos', 'etf', 'plazo fijo', 'inflacion', 'inflación', 'presupuestar',
      'gastos fijos', 'gastos variables', 'ingreso extra', 'side hustle',
      'deuda hipotecaria', 'hipoteca', 'alquiler', 'renta', 'nomina', 'nómina',
      'salario', 'sueldo', 'finanzas personales', 'riqueza', 'patrimonio',
      'gasto hormiga', 'regla 50 30 20', 'metodo sobre', 'método sobre',
    ],
    milestones: [
      'Hacer un diagnóstico completo: listar todos los ingresos, gastos fijos y deudas de un mes',
      'Identificar y eliminar al menos un gasto innecesario recurrente',
      'Definir un monto de ahorro mensual realista y automatizarlo',
      'Acumular el primer mes de tu objetivo (o pagar la primera cuota extra de deuda)',
      'Alcanzar tu meta financiera concreta: fondo de emergencia, viaje o inversión inicial',
    ],
    actions: [
      'Registrar todos los gastos de hoy con su categoría y monto exacto',
      'Revisar una suscripción activa y decidir si realmente la estás usando',
      'Transferir el ahorro de esta semana a tu cuenta o alcancía separada',
      'Comparar precios de la próxima compra grande en al menos dos tiendas',
      'Anotar una idea concreta para generar un ingreso extra este mes',
      'Revisar el estado de tu deuda más cara y calcular cuánto pagarías de más en intereses',
      'Leer 15 min sobre un concepto de finanzas personales que desconoces',
    ],
    kickoffActions: [
      'Lista todos tus ingresos mensuales y todos tus gastos fijos en una hoja',
      'Revisa tus suscripciones activas (streaming, apps, membresías) y cancela las que no uses',
      'Define un monto de ahorro mensual realista, aunque sea pequeño',
      'Abre una cuenta o app separada dedicada solo a tu ahorro',
      'Calcula tu objetivo en dinero concreto y la fecha en la que quieres lograrlo',
    ],
    cadence: 'thrice_week',
    reviewEveryDays: 7,
  },
  {
    key: 'carrera',
    label: 'Conseguir trabajo / cambiar de carrera',
    emoji: '🚀',
    defaultArea: 'carrera',
    description: 'Conseguir un nuevo empleo, conseguir tu primer cliente freelance o dar el salto a otro sector.',
    keywords: [
      'trabajo', 'empleo', 'laburo', 'laboral', 'carrera', 'cv', 'currículum',
      'curriculum', 'entrevista', 'linkedin', 'portafolio', 'profesional',
      'freelance', 'cliente', 'clientes',
      'postular', 'postularme', 'vacante', 'reclutador', 'sueldo', 'renunciar',
      'cambiar de trabajo', 'cambio de carrera', 'reconversion', 'reconversión',
      'networking', 'red de contactos', 'headhunter', 'oferta laboral', 'carta',
      'carta de presentacion', 'carta de presentación', 'entrevista tecnica',
      'entrevista técnica', 'prueba tecnica', 'prueba técnica', 'salario',
      'negociar sueldo', 'negociacion salarial', 'negociación salarial',
      'contrato', 'remoto', 'teletrabajo', 'hibrido', 'híbrido', 'consultora',
      'agencia', 'sector', 'industria', 'reorientacion', 'reorientación',
    ],
    milestones: [
      'Actualizar el CV y el perfil de LinkedIn con logros concretos y métricas',
      'Definir 10 empresas o roles objetivo y hacer una lista de contactos clave',
      'Enviar las primeras 5 postulaciones personalizadas (no en serie)',
      'Conseguir la primera entrevista y preparar las respuestas para las preguntas más frecuentes',
      'Llegar a una instancia final de selección o recibir una oferta concreta',
    ],
    actions: [
      'Postularte a una vacante que realmente te interesa y personalizar la carta',
      'Mejorar una sección del CV con un logro cuantificado (número, porcentaje, plazo)',
      'Escribir a un contacto de tu red con un mensaje específico y real, no genérico',
      'Practicar en voz alta la respuesta a "cuéntame sobre ti" y cronometrarla',
      'Investigar a fondo una empresa objetivo: producto, cultura, noticias recientes',
      'Leer una oferta laboral y anotar qué habilidades necesitas fortalecer',
      'Conectar con una persona nueva en LinkedIn con un mensaje personalizado',
    ],
    kickoffActions: [
      'Actualiza tu CV eliminando lo desactualizado y sumando resultados concretos',
      'Revisa y optimiza tu perfil de LinkedIn: foto profesional, titular y resumen',
      'Lista 5 empresas o roles donde quisieras trabajar y guarda las URLs',
      'Define con claridad qué tipo de trabajo buscas: sector, modalidad y rango salarial',
      'Escribe a un contacto de tu red que pueda orientarte o presentarte a alguien',
    ],
    cadence: 'weekdays',
    reviewEveryDays: 7,
  },
  {
    key: 'crecer_trabajo',
    label: 'Crecer en mi trabajo actual',
    emoji: '📈',
    defaultArea: 'carrera',
    description: 'Destacar en tu puesto, ganarte un ascenso o un aumento, y desarrollar habilidades de liderazgo.',
    keywords: [
      'ascenso', 'ascender', 'promoción', 'promocion', 'aumento', 'subir de puesto',
      'mejorar en mi trabajo', 'mejorar en el trabajo', 'mi trabajo', 'ser el mejor',
      'ser mejor', 'destacar', 'sobresalir', 'desempeño', 'desempeno', 'rendimiento',
      'productividad', 'liderazgo', 'liderar', 'lider', 'líder', 'jefe', 'jefa',
      'equipo', 'evaluación de desempeño', 'evaluacion de desempeño', 'feedback',
      'crecer profesionalmente', 'desarrollo profesional', 'crecimiento profesional',
      'habilidades blandas', 'soft skills', 'hablar en público', 'hablar en publico',
      'presentaciones', 'gestión del tiempo', 'gestion del tiempo', 'organizarme',
      'delegar', 'reuniones', 'kpi', 'okr', 'objetivos del trimestre', 'visibilidad',
      'reconocimiento', 'ganar más', 'ganar mas', 'senior', 'gerente', 'coordinador',
      'coordinadora', 'responsabilidades', 'proyecto importante', 'promovido',
      'promovida', 'plan de carrera',
    ],
    milestones: [
      'Definir qué significa "crecer" para ti: ascenso, aumento, nuevas responsabilidades o dominio del rol',
      'Hablar con tu jefe o líder para alinear expectativas y saber qué se espera para el siguiente nivel',
      'Completar un proyecto visible con un resultado medible que puedas mostrar',
      'Documentar tus logros del período con números y presentar tu caso (o recibir tu evaluación)',
      'Conseguir el avance concreto: el ascenso, el aumento o el nuevo alcance de rol',
    ],
    actions: [
      'Avanzar 30 min en el proyecto que más visibilidad le da a tu trabajo',
      'Anotar un logro de esta semana con su impacto medible (número, plazo o ahorro)',
      'Pedir feedback concreto a un colega o a tu líder sobre algo que hiciste',
      'Preparar tu próxima reunión con agenda y una propuesta, no solo asistencia',
      'Dedicar 20 min a una habilidad que tu siguiente nivel exige (presentar, delegar, analizar)',
      'Resolver un problema del equipo que nadie está tomando y dejarlo documentado',
      'Revisar tus prioridades de la semana y eliminar una tarea que no aporta a tus objetivos',
    ],
    kickoffActions: [
      'Escribe qué puesto, alcance o reconocimiento quieres tener en 6-12 meses',
      'Lista los 3 logros más fuertes que ya tienes y los 3 que te faltan para el siguiente nivel',
      'Agenda una conversación con tu jefe para alinear qué se espera de ti para crecer',
      'Crea un documento de logros y anota ahí cada resultado medible desde hoy',
      'Identifica la habilidad que más te frena y busca cómo practicarla esta semana',
    ],
    cadence: 'weekdays',
    reviewEveryDays: 7,
  },
  {
    key: 'crear_publicar',
    label: 'Crear o publicar algo',
    emoji: '🎨',
    defaultArea: 'creatividad',
    description: 'Lanzar un proyecto creativo o de contenido: newsletter, canal, blog, libro, música o portafolio.',
    keywords: [
      'escribir', 'libro', 'canal', 'youtube', 'portafolio', 'proyecto', 'crear',
      'publicar', 'blog', 'podcast', 'arte', 'contenido', 'app',
      'marca', 'newsletter', 'instagram',
      'tiktok', 'novela', 'música', 'musica', 'disco',
      'lanzar', 'lanzamiento', 'audiencia', 'comunidad',
      'seguidores', 'monetizar', 'monetizacion', 'monetización', 'marca personal',
      'personal brand', 'substack', 'patreon',
      'figma', 'diseño web', 'landing page',
      'software', 'aplicacion', 'aplicación', 'videojuego', 'game dev',
      'curso online', 'infoproducto', 'ebook', 'guía', 'guia', 'webinar',
      'twitch', 'streaming', 'reel', 'short', 'video corto', 'threads',
      'arte digital', 'ilustracion', 'ilustración', 'comic', 'cómic',
      'fotografo', 'fotógrafo', 'vender fotos', 'stock photos',
    ],
    milestones: [
      'Definir tu versión mínima publicable: ¿qué es lo mínimo que puede ver alguien externo?',
      'Producir y publicar tu primera pieza aunque sea imperfecta',
      'Conseguir tus primeros 10 lectores, suscriptores o usuarios reales',
      'Publicar de forma consistente durante 30 días (una cadencia sostenible)',
      'Alcanzar tu primer hito de tracción: 100 seguidores, primera venta o primer cliente',
    ],
    actions: [
      'Trabajar 30 min en modo creativo profundo: sin redes, sin interrupciones',
      'Crear una pieza pequeña de contenido y programarla o publicarla',
      'Revisar y mejorar una pieza existente antes de publicarla',
      'Interactuar con 5 personas de tu audiencia potencial para entender qué necesitan',
      'Anotar 3 ideas de contenido o producto para la próxima semana',
      'Analizar métricas de lo ya publicado e identificar qué funcionó mejor',
      'Documentar un proceso o aprendizaje que puedas compartir con tu audiencia',
    ],
    kickoffActions: [
      'Define en una frase qué vas a crear, para quién y qué problema resuelve',
      'Anota tu versión mínima publicable: lo más pequeño que podrías lanzar esta semana',
      'Crea el canal, cuenta o repositorio donde vas a publicar y configura el perfil',
      'Bloquea 30 min en tu agenda para trabajar en esto hoy mismo',
      'Publica algo pequeño ahora para romper la inercia, aunque sea un borrador o una idea',
    ],
    cadence: 'thrice_week',
    reviewEveryDays: 7,
  },
  {
    key: 'emprender',
    label: 'Emprender o hacer crecer un negocio',
    emoji: '💼',
    defaultArea: 'carrera',
    description: 'Validar una idea, conseguir tus primeras ventas o llevar tu negocio actual al siguiente nivel.',
    keywords: [
      'emprender', 'emprendimiento', 'negocio', 'startup', 'empresa', 'tienda',
      'vender', 'ventas', 'ecommerce', 'shopify', 'woocommerce', 'etsy', 'saas',
      'mvp', 'prototipo', 'producto', 'servicio', 'facturar', 'facturación',
      'facturacion', 'primeras ventas', 'primer cliente', 'clientes nuevos',
      'modelo de negocio', 'plan de negocio', 'validar', 'validación', 'validacion',
      'mercado', 'nicho', 'propuesta de valor', 'precio', 'precios', 'proveedores',
      'inventario', 'local', 'restaurante', 'cafetería', 'cafeteria', 'marca propia',
      'sociedad', 'socio', 'socia', 'escalar', 'crecer el negocio', 'mi negocio',
      'mi empresa', 'dropshipping', 'importar', 'exportar', 'franquicia',
    ],
    milestones: [
      'Definir tu propuesta: qué vendes, a quién y qué problema le resuelve',
      'Validar con clientes reales: 10 conversaciones o una versión mínima a la venta',
      'Conseguir la primera venta (o las primeras ventas del nuevo producto/canal)',
      'Repetir lo que funciona: proceso de venta documentado y clientes recurrentes',
      'Alcanzar tu primer objetivo de facturación o crecimiento sostenido mensual',
    ],
    actions: [
      'Hablar hoy con un cliente potencial o actual y anotar qué necesita realmente',
      'Trabajar 30 min en el producto o servicio: mejorarlo, empaquetarlo o simplificarlo',
      'Hacer una acción de venta concreta: propuesta enviada, publicación o seguimiento',
      'Revisar los números de la semana: qué entró, qué salió y qué margen queda',
      'Probar un canal nuevo de captación con un experimento pequeño y medible',
      'Documentar un proceso del negocio para que no dependa solo de tu memoria',
      'Analizar a un competidor y anotar una cosa que hace mejor y una oportunidad tuya',
    ],
    kickoffActions: [
      'Escribe tu propuesta en una frase: vendo X a Y porque les resuelve Z',
      'Define tu objetivo de los próximos 90 días en un número: ventas, clientes o facturación',
      'Lista 10 clientes potenciales concretos y contacta al primero hoy',
      'Calcula tus costos y define un precio con margen real',
      'Elige UN canal de venta para empezar y prepara lo mínimo para vender por ahí',
    ],
    cadence: 'weekdays',
    reviewEveryDays: 7,
  },
  {
    key: 'academico',
    label: 'Meta académica',
    emoji: '🎓',
    defaultArea: 'aprendizaje',
    description: 'Aprobar una materia, terminar la tesis, preparar unas oposiciones o conseguir una certificación.',
    keywords: [
      'tesis', 'materia', 'examen', 'graduar', 'graduarme', 'universidad', 'parcial',
      'académico', 'academico', 'monografía', 'monografia', 'facultad', 'aprobar',
      'oposiciones', 'oposición', 'oposicion', 'mba', 'doctorado', 'maestría',
      'maestria', 'posgrado', 'licenciatura', 'rendir', 'beca', 'toefl', 'ielts',
      'cursada', 'trabajo final', 'trabajo de fin de grado', 'tfg', 'tfm',
      'certificacion', 'certificación', 'certificado', 'diplomado', 'bootcamp',
      'cohorte', 'modulo', 'módulo', 'unidad', 'cuatrimestre', 'semestre',
      'tesina', 'disertacion', 'disertación', 'investigacion', 'investigación',
      'revisar apuntes', 'estudiar para', 'preparar examen', 'nota', 'calificacion',
      'calificación', 'gpa', 'creditos', 'créditos', 'defensa', 'tribunal',
      'aws', 'google cloud', 'azure', 'pmp', 'scrum', 'agile', 'certificacion tecnica',
    ],
    milestones: [
      'Hacer un inventario completo: listar todo lo que hay que entregar, rendir o escribir',
      'Armar un cronograma con fechas límite reales y bloques de estudio semanales',
      'Completar el primer bloque grande de material (primer tercio del temario o capítulos)',
      'Terminar el contenido y hacer una revisión completa con ejercicios de repaso',
      'Entregar, rendir o presentar y cerrar este ciclo académico',
    ],
    actions: [
      'Estudiar un bloque de 45 min con el material del próximo examen o entrega',
      'Avanzar una sección de la tesis o trabajo escrito: introducción, marco teórico, etc.',
      'Resolver un ejercicio práctico o problema de práctica de examen',
      'Hacer un mapa conceptual o resumen de lo estudiado hoy en menos de una página',
      'Revisar el cronograma y ajustar el plan si estás atrasado o adelantado',
      'Leer los comentarios del docente sobre un trabajo anterior y anotar qué mejorar',
      'Preparar 5 preguntas posibles de examen y responderlas sin mirar los apuntes',
    ],
    kickoffActions: [
      'Lista todo lo que tienes que entregar o rendir con sus fechas exactas',
      'Arma un cronograma semana a semana con bloques de estudio realistas',
      'Reúne todo el material: libros, apuntes, bibliografía y guárdalos en una carpeta',
      'Estudia el primer bloque de 45 min para arrancar con momentum',
      'Define una meta específica para esta semana: qué vas a terminar o repasar',
    ],
    cadence: 'weekdays',
    reviewEveryDays: 7,
  },
  {
    key: 'bienestar',
    label: 'Hábito de bienestar',
    emoji: '🌱',
    defaultArea: 'bienestar',
    description: 'Incorporar un hábito que mejore tu salud mental: dormir mejor, meditar, leer o manejar el estrés.',
    keywords: [
      'dormir', 'sueño', 'sueno', 'leer', 'lectura', 'meditar', 'meditación',
      'meditacion', 'estrés', 'estres', 'bienestar', 'calma', 'rutina', 'mindfulness',
      'fumar', 'tabaco', 'vapear', 'ansiedad', 'terapia', 'gratitud', 'hábito',
      'habito', 'descansar', 'desconectar', 'respiración', 'respiracion',
      'autocuidado', 'burnout', 'agotamiento', 'mental', 'salud mental',
      'depresion', 'depresión', 'estres cronico', 'estrés crónico', 'relajar',
      'relajación', 'relajacion', 'higiene del sueño', 'insomnio', 'despertar',
      'rutina matutina', 'rutina nocturna', 'journaling', 'diario', 'escritura',
      'terapia psicologica', 'psicólogo', 'psicologo', 'biohacking', 'cold shower',
      'ducha fría', 'ducha fria', 'sauna', 'ayuno', 'alcohol', 'dejar de beber',
      'dejar el alcohol', 'adiccion', 'adicción', 'pantallas', 'redes sociales',
      'detox digital', 'límites', 'limites', 'asertividad',
    ],
    milestones: [
      'Elegir UN hábito concreto, definir un horario fijo y preparar el entorno para hacerlo fácil',
      'Sostener el hábito durante 7 días seguidos sin saltarte ninguno',
      'Sostenerlo 21 días y notar el primer cambio real en cómo te sientes',
      'Llegar a 60 días: el hábito ya no requiere fuerza de voluntad, es parte de tu rutina',
      'Integrar el hábito como parte de tu identidad y evaluar si quieres sumar uno nuevo',
    ],
    actions: [
      'Practicar tu hábito de bienestar de hoy según el horario que elegiste',
      'Hacer una sesión de meditación o respiración consciente de 10 minutos',
      'Leer 15 páginas de un libro que estés disfrutando sin el teléfono cerca',
      'Apagar todas las pantallas 30 min antes de acostarte y preparar el cuarto para dormir',
      'Escribir en tu diario: tres cosas concretas por las que estás agradecido hoy',
      'Salir 15 minutos a caminar o al aire libre sin auriculares y sin teléfono',
      'Identificar el disparador principal de tu estrés de esta semana y escribir una respuesta posible',
    ],
    kickoffActions: [
      'Elige un único hábito de bienestar y define en qué momento exacto del día lo harás',
      'Prepara el entorno esta noche para que hacerlo mañana sea automático',
      'Practica el hábito hoy por primera vez, aunque sea durante 5 minutos',
      'Elimina la distracción principal que sabotea este hábito de tu entorno inmediato',
      'Anota cómo te sientes antes de empezar para tener una línea de base real',
    ],
    cadence: 'daily',
    reviewEveryDays: 7,
  },
  {
    key: 'relaciones',
    label: 'Mejorar mis relaciones',
    emoji: '🤝',
    defaultArea: 'relaciones',
    description: 'Invertir tiempo de calidad en la familia, la pareja, los amigos o construir nuevas amistades.',
    keywords: [
      'familia', 'pareja', 'amigos', 'amigas', 'relación', 'relacion', 'relaciones',
      'social', 'novia', 'novio', 'hijos', 'hijo', 'hija', 'vínculo', 'vinculo',
      'esposa', 'esposo', 'marido', 'padres', 'hermano', 'hermana', 'amistad',
      'citas', 'reconectar', 'comunicacion', 'comunicación', 'conflicto', 'conflictos',
      'intimidad', 'confianza', 'conocer gente', 'hacer amigos', 'soledad',
      'red social', 'comunidad', 'pertenencia', 'pareja terapia', 'terapia de pareja',
      'convivencia', 'discusiones', 'límites', 'limites', 'apego', 'amor',
      'enamorarse', 'citas romanticas', 'citas románticas', 'aplicaciones citas',
      'tinder', 'bumble', 'hinge', 'relacion abierta', 'relación abierta',
      'padre', 'madre', 'abuelos', 'nietos', 'primos', 'sobrinos',
    ],
    milestones: [
      'Identificar las 2 o 3 relaciones que más quieres nutrir y por qué',
      'Agendar un momento de calidad semanal con cada persona y cumplirlo sin cancelar',
      'Tener una conversación honesta y profunda que llevas tiempo posponiendo',
      'Sostener el hábito de dedicación durante un mes y notar el cambio en el vínculo',
      'Celebrar el progreso: esa relación hoy es más fuerte y consciente que al empezar',
    ],
    actions: [
      'Llamar (de verdad, con voz) a alguien importante que no hayas contactado esta semana',
      'Planear un momento específico juntos para esta semana: hora, lugar y actividad',
      'Preguntar a alguien cómo está y escuchar de verdad durante 10 minutos sin dar consejos',
      'Escribir un mensaje de agradecimiento sincero y específico a alguien que te importa',
      'Compartir algo personal contigo mismo primero: ¿qué necesitas en tus relaciones?',
      'Dejar el teléfono guardado durante una comida o conversación importante hoy',
      'Organizar un plan grupal o una actividad nueva con personas que ya conoces',
    ],
    kickoffActions: [
      'Anota las 2 o 3 personas con quienes quieres mejorar tu relación y por qué',
      'Manda un mensaje hoy mismo a una de ellas, genuino y sin excusas',
      'Agenda un momento concreto juntos esta semana con día, hora y plan',
      'Llama a alguien a quien tengas ganas de reconectar y que hace mucho no escuchas',
      'Escribe qué tipo de presencia quieres ser para las personas que te importan',
    ],
    cadence: 'thrice_week',
    reviewEveryDays: 7,
  },
  {
    key: 'personalizada',
    label: 'Meta personalizada',
    emoji: '🎯',
    defaultArea: 'otra',
    description: 'Tú defines el objetivo, las etapas y el ritmo. Para cuando ninguna categoría encaja.',
    keywords: [],
    milestones: [
      'Definir el resultado final concreto y cómo sabrás que lo lograste',
      'Dividir el camino en 3 o 4 hitos grandes y ordenarlos por prioridad',
      'Completar el primer hito y evaluar si el plan sigue siendo correcto',
      'Completar el segundo hito y ajustar el enfoque si es necesario',
      'Llegar al resultado final y celebrar el logro con una revisión de lo aprendido',
    ],
    actions: [
      'Avanzar 25 min en la tarea más importante de tu meta de esta semana',
      'Definir el siguiente paso concreto y anotarlo como acción de mañana',
      'Revisar tu progreso honestamente: ¿estás más cerca del hito? ¿Qué frena el avance?',
      'Eliminar un obstáculo o distracción que está bloqueando tu progreso',
      'Dedicar 20 min a investigar, aprender o planificar lo que necesitas para el siguiente paso',
      'Compartir tu avance con alguien de confianza para mantener accountability',
    ],
    kickoffActions: [
      'Escribe en una sola frase cuál es el resultado final que quieres lograr',
      'Lista todos los pasos posibles y elige los 3 o 4 más importantes como hitos',
      'Define qué harás esta semana como primer avance concreto',
      'Busca a alguien que ya logró algo similar y estudia cómo lo hizo',
      'Bloquea en tu agenda el tiempo semanal que le vas a dedicar a esta meta',
    ],
    cadence: 'thrice_week',
    reviewEveryDays: 7,
  },
]

const TEMPLATE_BY_KEY = new Map(TEMPLATES.map((t) => [t.key, t]))

/** Plantilla por clave. Cae en 'personalizada' si la clave no existe (datos viejos). */
export function getTemplate(key: string): GoalTemplate {
  return TEMPLATE_BY_KEY.get(key) ?? TEMPLATE_BY_KEY.get('personalizada')!
}

/** Plantillas que sugiere por defecto un nicho (la propia primero). */
export function templatesForNiche(niche: NicheId): GoalTemplate[] {
  const own = TEMPLATES.filter((t) => t.defaultArea === niche && t.key !== 'personalizada')
  const rest = TEMPLATES.filter((t) => t.defaultArea !== niche)
  return [...own, ...rest]
}

/**
 * Detecta la plantilla más probable a partir del título de la meta contando
 * coincidencias de palabras clave. Es una sugerencia: el usuario siempre puede
 * cambiarla. Si no hay señal clara, devuelve 'personalizada'.
 */
export function detectTemplate(title: string): GoalTemplate {
  const text = ` ${title.toLowerCase()} `
  let best = getTemplate('personalizada')
  let bestScore = 0
  for (const template of TEMPLATES) {
    let score = 0
    for (const kw of template.keywords) {
      if (text.includes(kw)) score += 1
    }
    if (score > bestScore) {
      bestScore = score
      best = template
    }
  }
  return best
}
