import type { LearnCollection } from '@/lib/types'

/**
 * Contenido de la zona Aprender: micro-lecciones de crecimiento personal.
 *
 * Es contenido estático y curado (no viene de la base de datos) porque la
 * propuesta es editorial: pocas lecciones, bien escritas, cada una con una
 * acción aplicable hoy. El progreso de lectura vive en el cliente.
 *
 * Cada lección tiene dos modos de lectura: `idea` (resumen, ~80 palabras)
 * e `ideaLong` (a fondo, 250-350 palabras con mecanismo, ejemplo y matiz).
 *
 * El ORDEN del array es el orden de prioridad que ve el usuario y sigue la
 * secuencia lógica para lograr metas según la literatura estándar:
 *   1) Primero, claridad — sin un foco claro, nada de lo demás funciona:
 *      hábitos, enfoque y constancia necesitan saber a qué servir.
 *   2) Hábitos que se quedan — el motor de ejecución: convierte la meta
 *      elegida en repeticiones que no dependen de la motivación.
 *   3) Enfoque real — proteger la atención diaria para que las horas de
 *      trabajo rindan de verdad.
 *   4) Constancia sin culpa — sostener todo lo anterior en el tiempo,
 *      incluyendo tropiezos, pausas y regresos.
 * (La pantalla solo antepone las colecciones del área de foco del usuario
 * con un sort estable; el resto conserva este orden.)
 */
export const LEARN_COLLECTIONS: LearnCollection[] = [
  {
    id: 'primero-claridad',
    title: 'Primero, claridad',
    blurb: 'Elegir qué importa y diseñar el día antes de correr a hacerlo todo.',
    area: 'carrera',
    lessons: [
      {
        id: 'una-meta-primero',
        title: 'Una meta a la vez',
        idea: 'Perseguir cinco metas a la vez casi garantiza no lograr ninguna: la energía se reparte tan delgada que el avance en cada frente se vuelve invisible, y sin avance visible la motivación se apaga. Elegir una meta prioritaria no es renunciar a las demás: es ponerlas en fila. Una meta clara ordena tus decisiones diarias; cinco metas difusas las dispersan. Menos es más cuando "menos" significa lo que de verdad importa ahora.',
        ideaLong:
          'Tu energía y tu tiempo son fijos: cada meta nueva no suma capacidad, divide la que ya tienes. Con cinco frentes abiertos, cada uno recibe un quinto de tu atención, y un quinto rara vez alcanza para cruzar el umbral donde el progreso se nota. Y ahí está el verdadero costo: el avance invisible desmotiva. No abandonas tus metas porque sean difíciles; las abandonas porque después de semanas de esfuerzo repartido no ves resultados en ninguna.\n\nPiensa en alguien que arranca el año queriendo ahorrar, aprender inglés, correr tres veces por semana y leer más. En enero hace un poco de todo; en marzo, nada de nada: cada frente avanzó tan poco que ninguno generó la evidencia de progreso que sostiene el esfuerzo. Compáralo con su versión alternativa: elige solo el inglés, estudia veinte minutos diarios, y en marzo ya entiende series sin subtítulos. Ese resultado visible no solo consolida esa meta: le enseña cómo se logra una, y esa habilidad se transfiere a la siguiente.\n\nEl matiz importante: priorizar no es abandonar. Las otras metas van a una lista de espera explícita, con fecha de revisión, no al olvido. Saber que "correr" espera su turno en junio libera la culpa de no estar corriendo hoy. El error común es el contrario: mantener todas las metas "activas" en la cabeza, donde cada una funciona como un reproche de fondo que gasta energía sin producir nada. Una meta activa y cuatro en pausa consciente rinde más que cinco a medias. La pregunta que ordena todo: si solo pudieras lograr una este año, ¿cuál cambiaría más tu vida?',
        apply: 'Escribe tus metas actuales en una lista, elige UNA como prioritaria y marca las demás como "en espera" con una fecha para revisarlas. En la app, ponle la estrella de prioridad a esa meta.',
      },
      {
        id: 'la-unica-cosa',
        title: 'La única cosa del día',
        idea: 'De tus diez pendientes de hoy, uno o dos producen la mayor parte del avance real; el resto es mantenimiento. Tratarlos a todos por igual es la trampa: terminas el día agotado de tareas menores con lo importante intacto. Antes de empezar, identifica la tarea que más acerca tu meta y dale el primer lugar, no el que sobre. Una cosa importante terminada vale más que diez pequeñas tachadas.',
        ideaLong:
          'No todas las tareas valen lo mismo, pero tu lista de pendientes las presenta como si sí: "responder correos" ocupa el mismo renglón que "preparar la propuesta que define el trimestre". Ese formato plano esconde una realidad desigual: en casi cualquier lista, una minoría de tareas produce la mayoría del avance. Es el principio de Pareto aplicado al día: el 20% de lo que haces genera el 80% de lo que logras. El problema es que ese 20% suele ser lo difícil, lo que no urge, lo que nadie te reclama hoy, y por eso pierde siempre contra lo pequeño y ruidoso.\n\nMíralo en un día concreto: alguien que quiere cambiar de trabajo tiene en su lista "actualizar el CV", junto con lavar ropa, contestar mensajes y hacer mercado. A las diez de la noche, todo está tachado menos el CV. Repetido durante tres meses, el resultado es una casa impecable y la misma vida. No falló por pereza: falló por orden. Hizo primero lo fácil, y lo importante quedó para una energía que ya no existía.\n\nLa corrección es un ritual de treinta segundos: antes de abrir la lista, pregúntate cuál es la única cosa que, hecha hoy, más acerca tu meta o hace el resto más fácil o innecesario. Esa tarea no se agrega a la lista: la encabeza, y se hace primero o en tu mejor bloque de energía. El error común es elegir tres "únicas cosas": si todo es prioridad, nada lo es. Una sola. Los pendientes menores caben en los huecos del día; tu única cosa no sobrevive en los huecos.',
        apply: 'Antes de abrir tu lista de hoy, escribe la respuesta a: "¿Qué única cosa, hecha hoy, acerca más mi meta?". Hazla primero, antes del correo y los mensajes.',
        cta: { kind: 'habit', title: 'Elegir mi única cosa del día', area: 'carrera' },
      },
      {
        id: 'disena-manana-hoy',
        title: 'Diseña mañana esta noche',
        idea: 'Un día sin plan se llena solo: con lo urgente, con lo que otros piden, con la primera notificación. Planear en la mañana tampoco funciona bien: gastas tu mejor energía decidiendo en vez de haciendo. La solución cuesta cinco minutos la noche anterior: decide qué harás mañana, en qué orden y cuándo. Despiertas con un día ya decidido, y decidir es la mitad del trabajo.',
        ideaLong:
          'Cada decisión gasta energía mental, y esa energía es la misma que necesitas para el trabajo importante. Por eso las mañanas sin plan son tan caras: despiertas y lo primero que haces es deliberar —¿por dónde empiezo?, ¿el correo o el informe?, ¿gimnasio hoy o mañana?—, y cada deliberación cobra su parte antes de que hayas producido nada. Peor: un día sin decisiones previas queda a merced del entorno, y el entorno siempre tiene un plan para ti hecho de notificaciones, pedidos ajenos y urgencias menores.\n\nPlanear la noche anterior invierte la ecuación. Cinco minutos antes de cerrar el día: escribes tus tres prioridades de mañana, marcas cuál es la primera y decides en qué momento harás cada una. No es una lista de deseos: es una cita con cada tarea. La diferencia se nota en la primera hora: quien planeó abre la laptop y ejecuta; quien no, abre la laptop y "revisa un momento" el correo, y ese momento se come la mañana. Además, tu yo de la noche planea mejor: tiene el contexto del día fresco y sabe exactamente qué quedó a medias y qué viene.\n\nHay un beneficio secundario que casi nadie espera: se duerme mejor. Los pendientes sin decidir rondan la cabeza en la noche precisamente porque están abiertos; escribirlos con un cuándo los cierra, y el cerebro los suelta. El error común es planear de más: doce tareas en bloques de quince minutos es una fantasía que se rompe a las 9:40 y desacredita todo el plan. Tres prioridades realistas, la primera bien elegida, y espacio libre para lo que siempre surge. Un plan que sobrevive al día real vale más que uno perfecto que no.',
        apply: 'Esta noche, antes de dormir, escribe las tres prioridades de mañana y subraya cuál harás primero. Déjalas donde las veas al despertar.',
        cta: { kind: 'habit', title: 'Planear mañana en 5 minutos antes de dormir', area: 'carrera' },
      },
      {
        id: 'empieza-pequeno',
        title: 'Empieza ridículamente pequeño',
        idea: 'Lo que paraliza no es la meta: es la distancia entre la meta y este momento. "Escribir un libro" no cabe en un martes a las 7 pm; "escribir una frase" sí. Reducir el primer paso hasta que dé casi vergüenza no es falta de ambición: es ingeniería. Empezar es la parte más cara de cualquier tarea, y un paso diminuto la vuelve gratis. Ya en movimiento, seguir es fácil.',
        ideaLong:
          'Toda tarea tiene un costo de arranque: el momento de pasar de no hacerla a hacerla. Ese costo no depende del tamaño real del trabajo sino del tamaño percibido del primer paso, y ahí está el problema de las metas grandes: "montar mi negocio" o "ponerme en forma" no tienen primer paso visible, así que el cerebro las clasifica como amenaza difusa y las pospone. La procrastinación casi nunca es pereza; es parálisis frente a un paso demasiado grande para caber en el momento presente.\n\nLa solución es reducir el paso hasta que la resistencia desaparezca. No "hacer el plan de negocio": abrir un documento y escribirle el título. No "salir a correr 5 km": ponerse las zapatillas y pisar la calle. Suena trivial, y esa es exactamente la señal de que está bien calibrado. Porque una vez en movimiento opera otra fuerza: continuar una tarea empezada cuesta mucho menos que empezarla. Quien abrió el documento "solo para el título" suele escribir un párrafo; quien pisó la calle "solo un momento" suele caminar veinte minutos. El paso diminuto no era la meta: era la puerta.\n\nEl error común es avergonzarse del paso pequeño y volver a inflarlo: "una frase es ridículo, mejor escribo una hora", y como una hora no cabe hoy, no se escribe nada. Compara los saldos: la versión ridícula, repetida a diario, produce páginas en un mes; la versión ambiciosa, pospuesta a diario, produce cero. El progreso no les pertenece a quienes planean pasos impresionantes, sino a quienes dan pasos que sí ocurren. Ridículo y hecho le gana a perfecto y pendiente, todos los días.',
        apply: 'Toma la meta que más has pospuesto y escribe un primer paso tan pequeño que puedas hacerlo en los próximos 10 minutos. Hazlo ahora: el objetivo de hoy no es avanzar mucho, es romper el cero.',
      },
      {
        id: 'mide-lo-que-importa',
        title: 'Mide lo que importa',
        idea: 'Lo que mides, mejora; lo que no mides, se estanca sin que lo notes. Pero medir lo equivocado también cuesta: el resultado final (el peso, el saldo) se mueve lento y con ruido, y mirarlo a diario desanima. Mide mejor la acción que lo produce: entrenamientos completados, dinero transferido, páginas escritas. Sobre la acción tienes control hoy; el resultado llega solo, de a poco, como consecuencia.',
        ideaLong:
          'Sin un número, tu progreso queda en manos de tu memoria y tu ánimo, dos jueces pésimos: recuerdan lo que faltó, olvidan lo que hiciste y dictan sentencia según cómo dormiste. Medir corrige eso con evidencia. Pero hay una decisión previa que casi nadie toma en serio: qué medir. Toda meta tiene dos tipos de números: los de resultado (el peso en la báscula, el saldo ahorrado, el nivel de inglés) y los de acción (entrenamientos completados, transferencias hechas, sesiones de estudio). Los de resultado son los que te importan, pero no los controlas directamente y se mueven lento y con ruido. Los de acción son aburridos, pero están completamente en tus manos, hoy.\n\nMira lo que pasa cuando alguien mide solo el resultado: se pesa cada mañana, y la báscula —que fluctúa por agua, sal y azar— le dice un día que bajó y al siguiente que subió, sin relación con su esfuerzo real. A la tercera semana de señales confusas, abandona. Su error no fue de disciplina: fue de tablero. Si hubiera medido "entrenamientos de esta semana: 4 de 4", habría visto una línea que sí responde a lo que hace, y esa respuesta inmediata es combustible.\n\nLa práctica sana: elige UN número de acción por meta y revísalo cada semana; el resultado, míralo una vez al mes, como quien revisa que el mapa siga coincidiendo con el camino. El error común es el exceso: paneles con ocho métricas que nadie actualiza después del primer viernes. Un solo número que sí registras vale más que ocho que no. Y cuando la acción se cumple semana tras semana y el resultado no llega, el número te dice algo igual de valioso: no es falta de esfuerzo, es hora de cambiar de método.',
        apply: 'Elige el número de acción de tu meta prioritaria (sesiones, páginas, transferencias) y anota su valor de esta semana. Ese registro semanal es tu nuevo tablero.',
        cta: { kind: 'habit', title: 'Registrar mi avance de la semana', area: 'carrera' },
      },
    ],
  },
  {
    id: 'habitos-que-quedan',
    title: 'Hábitos que se quedan',
    blurb: 'Cómo construir rutinas que sobreviven a la motivación inicial.',
    area: 'bienestar',
    lessons: [
      {
        id: 'identidad-antes-que-resultados',
        title: 'Empieza por quién quieres ser',
        idea: 'Los hábitos que duran no nacen de "quiero correr 5 km", sino de "soy alguien que entrena". Cuando la meta es un resultado, el hábito muere al alcanzarlo o al frustrarte. Cuando la meta es una identidad, cada repetición es un voto a favor de esa persona, y los votos se acumulan aunque el resultado tarde.',
        ideaLong:
          'Hay dos formas de perseguir el mismo hábito y solo una sobrevive. La primera apunta al resultado: "quiero bajar cinco kilos", "quiero terminar el curso". Funciona un tiempo, pero tiene dos fechas de muerte incorporadas: si logras el resultado, el hábito pierde su razón de ser; si tarda, la frustración lo mata antes. La segunda forma apunta a la identidad: "soy una persona que entrena", "soy alguien que estudia a diario". Esa no caduca, porque una identidad no se alcanza y se archiva: se ejerce.\n\nEl mecanismo es un círculo que se refuerza solo. Cada vez que actúas como la persona que quieres ser, generas una pequeña evidencia a favor de esa identidad —un voto—. Los votos se acumulan, la identidad se vuelve más creíble para ti mismo, y una identidad creíble hace la siguiente repetición más natural, casi obvia: la gente hace lo que las personas como ellas hacen. Se nota hasta en el lenguaje: quien dice "estoy intentando no fumar" pelea contra su deseo en cada oferta de cigarrillo; quien dice "no fumo" no pelea nada, solo describe quién es. La primera frase negocia; la segunda cierra el tema.\n\nEl matiz que evita el error clásico: la identidad no se declara primero y se actúa después. Nadie "se siente" corredor antes de correr; se corre —poco, mal, dos minutos— y la evidencia va construyendo al corredor. Por eso no esperes convicción para empezar: la convicción es el resultado de las repeticiones, no su requisito. Y por eso las versiones mínimas del hábito importan tanto: dos minutos no transforman tu cuerpo, pero emiten el voto completo. Cuando falles, el marco también te cuida: un mal día no te quita la identidad; solo fue un voto en contra, y vas ganando la elección.',
        apply: 'Escribe una frase con la identidad detrás de tu hábito más importante: "Soy una persona que ___". Ponla donde la veas al despertar y léela antes de decidir si hoy cumples.',
        cta: { kind: 'habit', title: 'Leer mi frase de identidad al despertar', area: 'bienestar' },
      },
      {
        id: 'regla-de-los-2-minutos',
        title: 'La regla de los 2 minutos',
        idea: 'Un hábito nuevo no fracasa por difícil: fracasa por grande. Reduce cualquier hábito a una versión que tome dos minutos: "meditar" se vuelve "sentarme y respirar tres veces"; "leer cada noche" se vuelve "leer una página". Al principio lo importante no es el resultado, es presentarte. Quien aparece dos minutos cada día puede después quedarse veinte.',
        ideaLong:
          'Cuando un hábito nuevo muere, casi siempre muere en el mismo lugar: el momento de empezar. No es que treinta minutos de ejercicio sean insoportables; es que la idea de treinta minutos, vista desde el sillón un martes cansado, pesa demasiado, y el cerebro elige el alivio inmediato de posponer. La regla de los dos minutos ataca exactamente ese punto: recorta el hábito hasta una versión tan pequeña que decir "no" cueste más esfuerzo que hacerla. "Salir a correr" se vuelve "ponerme las zapatillas y salir a la esquina". "Escribir el diario" se vuelve "escribir una oración".\n\nLa lógica que la sostiene: un hábito debe establecerse antes de poder mejorarse. Las primeras semanas no estás entrenando el cuerpo ni produciendo resultados: estás entrenando la aparición, el acto de presentarte a la misma hora sin negociar contigo mismo. Ese es el cimiento, y se construye con repeticiones, no con intensidad. Una vez que aparecer es automático, escalar es sencillo, porque empezar era la parte difícil: quien ya está con las zapatillas puestas en la calle rara vez vuelve a los dos minutos; quien ya leyó una página suele seguir. Y los días malos, la versión mínima cumple igual su función profunda: mantiene viva la cadena y tu identidad de persona que cumple.\n\nEl error común es sabotear la regla por orgullo: "¿de qué sirve una página?, mejor leo un capítulo", y como el capítulo no cabe hoy, no se lee nada. No confundas el techo con el piso: dos minutos es el mínimo que garantiza que el hábito ocurra, no el máximo permitido. Si un día das más, excelente. Pero el contrato contigo es por dos minutos, y un contrato pequeño que cumples a diario vale más que uno ambicioso que renegocias cada noche.',
        apply: 'Elige el hábito que más has pospuesto y escribe su versión de 2 minutos. Hazla hoy, aunque te parezca ridículamente pequeña: esa incomodidad es la señal de que está bien diseñada.',
        cta: { kind: 'habit', title: 'Leer una página antes de dormir', area: 'aprendizaje' },
      },
      {
        id: 'apilar-habitos',
        title: 'Apila sobre lo que ya haces',
        idea: 'Tu día ya está lleno de hábitos que nunca fallan: prepararte el café, lavarte los dientes, cerrar la laptop. Esos momentos son anclas gratis. En vez de confiar en la memoria o en la motivación, engancha el hábito nuevo justo después de uno existente: "después de servirme el café, escribo mis tres prioridades".',
        ideaLong:
          'Un hábito nuevo necesita un disparador: algo que le diga al cerebro "ahora toca esto". La mayoría de la gente usa disparadores vagos —"voy a meditar en las tardes", "haré estiramientos cuando pueda"— y ahí está la falla: "en las tardes" no es un momento, es una niebla, y los hábitos no sobreviven en la niebla. Necesitan un cuándo exacto. La buena noticia es que no hace falta inventarlo: tu rutina actual ya tiene decenas de momentos que ocurren todos los días sin fallar, a la misma hora, sin esfuerzo. Servirte el café. Lavarte los dientes. Sentarte en el carro. Cerrar la laptop.\n\nApilar hábitos es usar esas rutinas como anclas: "después de [hábito que ya tengo], hago [hábito nuevo]". El hábito viejo, con años de automatismo encima, se convierte en el disparador del nuevo, y el nuevo hereda su puntualidad. "Después de servirme el café de la mañana, escribo mis tres prioridades del día" funciona porque el café ocurre siempre: no dependes de acordarte ni de tener ganas; el café se encarga de ambas cosas. Con el tiempo, la secuencia se funde en un solo movimiento: café y prioridades, como llave y cerradura.\n\nDos detalles deciden si la pila funciona. Primero, el ancla debe ser verdaderamente estable: si desayunas a horas distintas o a veces no desayunas, esa ancla hará aguas; elige algo que ocurra a diario sin excepción. Segundo, la precisión importa: "después de que la cafetera termina, y antes de tomar el primer sorbo" le gana a "en el desayuno". El error común es apilar demasiado: cinco hábitos encadenados tras el café construyen un castillo de naipes donde un eslabón caído derrumba el resto. Un ancla, un hábito. Cuando ese ya no requiera pensarse, apila el siguiente.',
        apply: 'Completa hoy esta fórmula: "Después de [hábito que ya tengo], voy a [hábito nuevo de 2 minutos]". Pruébala esta misma tarde o mañana al despertar.',
        cta: { kind: 'habit', title: 'Escribir 3 prioridades después del café', area: 'carrera' },
      },
      {
        id: 'disena-el-entorno',
        title: 'Diseña el entorno, no la voluntad',
        idea: 'La fuerza de voluntad es un recurso que se agota; el entorno trabaja gratis las 24 horas. Hacemos lo que está a la vista y a un paso: si la fruta está en la mesa, la comes; si el celular está en el bolsillo, lo revisas. Cambiar el entorno una vez vale más que resistir la tentación cien veces.',
        ideaLong:
          'Nos gusta creer que nuestras decisiones nacen de adentro, pero una parte enorme nace del paisaje: hacemos lo que está visible y a un paso, y dejamos de hacer lo que está guardado y a tres. No comes las galletas porque decidiste comerlas; las comes porque estaban en la mesa, a la altura de los ojos, mientras el frutero quedó arriba de la nevera. Cada opción visible es una micro-tentación que exige una micro-decisión, y la fuerza de voluntad —que se gasta con el uso, como un músculo— pierde por acumulación: puedes resistir diez veces, pero la tentación compite cincuenta veces al día, y le basta ganar una.\n\nDiseñar el entorno invierte el juego: en lugar de ganarle a la tentación cada vez, la sacas de la cancha una sola vez. La regla tiene dos mitades. Para el hábito que quieres: redúcele pasos y ponlo en el camino —la guitarra en un atril en medio de la sala, no en su estuche en el clóset; el libro sobre la almohada; la ropa de gimnasio lista junto a la cama—. Para el que quieres evitar: agrégale pasos —el celular cargando en la cocina durante la noche, las apps de redes fuera de la pantalla de inicio, sin cerrar sesión guardada—. Cada paso extra es un peaje, y los peajes disuaden más de lo que admitimos: quien tiene que levantarse hasta la cocina por el celular, muchas veces ya no va.\n\nEl error común es diseñar una vez y confiarse: el entorno se degrada solo —el celular vuelve a la mesa de noche, las galletas reaparecen en la despensa— y hay que re-diseñarlo como quien riega una planta. Y no olvides el entorno digital, donde pasas horas: tu pantalla de inicio es una mesa más; decide tú qué queda a la vista.',
        apply: 'Haz un cambio físico hoy: deja a la vista lo que quieres hacer (el libro sobre la almohada, las zapatillas junto a la puerta) y ponle fricción a lo que quieres evitar (el celular cargando en otra habitación).',
        cta: { kind: 'habit', title: 'Dejar el celular fuera del cuarto en la noche', area: 'bienestar' },
      },
      {
        id: 'nunca-falles-dos-veces',
        title: 'Nunca falles dos veces',
        idea: 'Fallar un día no rompe un hábito; lo rompe la espiral de fallar el segundo, el tercero y rendirse. Un error es un accidente; dos seguidos son el inicio de un hábito nuevo: el de no hacerlo. La regla es simple: puedes fallar, pero nunca dos veces seguidas. Así cada tropiezo es un punto de retorno, no una caída.',
        ideaLong:
          'Ningún hábito se rompe por un mal día. Se rompe por lo que ese mal día desencadena: el efecto "ya qué importa". Rompiste la dieta un viernes en un cumpleaños, y en lugar de tratarlo como lo que fue —una comida—, tu cabeza lo convierte en veredicto: "ya arruiné la semana", y con la semana "arruinada", el sábado y el domingo se vuelven tierra de nadie. El daño de la torta era mínimo; el daño del cuento que te contaste sobre la torta duró tres días. Así se pierden los hábitos: no en el tropiezo, sino en la licencia que el tropiezo parece otorgar.\n\nLa regla "nunca dos veces seguidas" corta esa espiral en el punto exacto. Acepta de entrada que vas a fallar —la vida garantiza viajes, virus y días imposibles— y convierte cada fallo en algo con fecha de vencimiento: mañana. Un día perdido es un accidente sin consecuencias estructurales; el segundo día consecutivo es otra cosa: es la primera repetición de un hábito nuevo, el de no hacerlo, y ese también se fortalece con cada repetición. La regla no te pide perfección; te pide que el regreso sea siempre inmediato.\n\nEl matiz práctico: el día siguiente a un fallo, el objetivo no es rendir, es votar. La versión mínima —los dos minutos, la página, la caminata a la esquina— cuenta completa, porque lo que está en juego ese día no es el resultado sino la narrativa: eres alguien que volvió, no alguien que abandonó. El error común es lo opuesto: querer compensar lo perdido con una sesión doble, que por pesada se pospone, y el "nunca dos veces" muere en el intento de hacerlo espectacular. Vuelve pequeño, pero vuelve mañana. Las personas constantes no fallan menos que el resto; regresan más rápido.',
        apply: 'Si ayer dejaste caer un hábito, hazlo hoy en su versión mínima. No para compensar lo perdido, sino para cortar la racha de fallos en uno.',
      },
      {
        id: 'recompensa-inmediata',
        title: 'Dale al hábito un premio hoy',
        idea: 'Tu cerebro repite lo que se siente bien ahora, no lo que será bueno en un año. Los hábitos saludables tienen un problema: su recompensa llega tarde. La solución es añadir una recompensa inmediata —marcar la casilla, tachar el día, el podcast que solo escuchas mientras caminas—. La satisfacción de hoy financia la constancia de mañana.',
        ideaLong:
          'El cerebro aprende por una regla simple: lo que se siente bien ahora, se repite; lo que se siente mal ahora, se evita. El problema es que los hábitos valiosos tienen los premios invertidos en el tiempo. El ejercicio cuesta hoy y paga en meses; el ahorro duele hoy y paga en años. Los malos hábitos ofrecen el trato contrario: el azúcar, la serie y el scroll pagan en segundos y cobran después. En esa competencia, el circuito de recompensa —que descuenta brutalmente todo lo futuro— elige siempre el premio cercano. No es falta de carácter: es la tabla de precios con la que vino el cerebro.\n\nLa jugada no es pelear contra esa tabla sino usarla: injertarle al hábito bueno una recompensa que llegue ya. Hay dos vías. Una es emparejar el hábito con un placer que solo ocurre durante él: el podcast que solo escuchas mientras caminas, la playlist que solo suena mientras ordenas, el café rico reservado para la sesión de estudio. Así el hábito deja de ser puro costo presente. La otra vía es el registro visible: marcar la casilla, tachar el día en el calendario. Suena trivial, pero ese check es una dosis pequeña y real de satisfacción, y la cadena de días marcados se convierte en algo que no quieres romper: el progreso visible es, en sí mismo, una recompensa.\n\nUn cuidado y un matiz. El cuidado: la recompensa no debe traicionar al hábito —premiar la corrida con una hamburguesa o el ahorro con una compra le paga al enemigo—; elige premios neutros o alineados. El matiz: el premio artificial es un puente, no una prótesis permanente. Con las semanas, el hábito genera sus propios pagos —energía, avance, la sensación de ser alguien que cumple— y el andamio externo se vuelve opcional. Pero al principio, ese andamio decide si el hábito llega vivo a ese punto.',
        apply: 'Elige una recompensa pequeña e inmediata para tu hábito principal y úsala hoy, justo al terminar. Marcarlo como cumplido en la app también cuenta: ese check existe para eso.',
      },
    ],
  },
  {
    id: 'enfoque-real',
    title: 'Enfoque real',
    blurb: 'Recuperar tu atención en un mundo diseñado para robártela.',
    area: 'carrera',
    lessons: [
      {
        id: 'bloques-cortos-profundos',
        title: 'Profundo en bloques cortos',
        idea: 'No necesitas cuatro horas libres para hacer trabajo profundo; necesitas 25 minutos sin interrupciones. Un bloque corto con el teléfono lejos y una sola pestaña abierta produce más que una tarde entera de atención fragmentada. La profundidad no se mide en horas: se mide en ausencia de interrupciones.',
        ideaLong:
          'El mito del trabajo profundo es que requiere mañanas enteras despejadas, y como esas mañanas nunca llegan, el trabajo importante espera para siempre. Pero la profundidad no es una función del tiempo total: es una función de la continuidad. El rendimiento intelectual se puede pensar como intensidad de foco multiplicada por tiempo: veinticinco minutos de atención intacta producen más que tres horas donde la atención se corta cada seis minutos, porque cada corte no resta solo el minuto de la interrupción, resta el costo de volver a profundizar. Una tarde fragmentada es, en la práctica, una tarde en la superficie.\n\nLa receta de un bloque profundo es corta y estricta: elige una sola tarea antes de empezar, pon el teléfono en otra habitación —no bocabajo: en otra habitación—, cierra todo lo que no sea esa tarea, y pon una alarma de veinticinco minutos. Hasta que suene, solo existe eso. Quien lo prueba por primera vez suele llevarse dos sorpresas: cuántas veces la mano viaja sola hacia el teléfono que ya no está, y cuánto avanza el informe que llevaba una semana "en proceso". Esa presión suave de la alarma también ayuda: un límite visible concentra, mientras que el tiempo infinito invita a divagar.\n\nEl matiz que hace la diferencia: el bloque protege de dos enemigos, no de uno. Las interrupciones externas —notificaciones, gente, mensajes— son el enemigo visible; las autointerrupciones son el invisible y más frecuente: nadie te escribió, pero fuiste tú a mirar. Por eso las reglas físicas (teléfono lejos, una pestaña) valen más que las intenciones ("no voy a mirar"). El error común es esperar el día libre perfecto para "ponerse de verdad". No existe. Existe el hueco de veinticinco minutos entre dos reuniones, y quien aprende a usarlo tiene una ventaja que los demás siguen esperando.',
        apply: 'Agenda hoy un bloque de 25 minutos para tu tarea más importante: silencia notificaciones, cierra lo que no uses y trabaja en una sola cosa hasta que suene la alarma.',
        cta: { kind: 'habit', title: 'Un bloque de 25 min sin interrupciones', area: 'carrera' },
      },
      {
        id: 'una-sola-cosa',
        title: 'Una sola cosa a la vez',
        idea: 'La multitarea es una ilusión: el cerebro no hace dos tareas cognitivas a la vez, alterna entre ellas y pierde calidad en ambas. Trabajar en una sola cosa no es lentitud: es la forma más rápida de terminar. La pregunta útil cada mañana es: ¿cuál es la única cosa que, si la termino hoy, hace que el día haya valido?',
        ideaLong:
          'La multitarea se siente productiva —tantas cosas en el aire a la vez— y esa sensación es precisamente la trampa. El cerebro no ejecuta dos tareas cognitivas en paralelo: alterna entre ellas a gran velocidad, y cada alternancia cobra un peaje de reorientación. El resultado medible es peor en todos los frentes: más tiempo total, más errores y menor calidad en ambas tareas. Quien responde correos durante una reunión no está haciendo dos cosas: está haciendo mal dos cosas por turnos, y la sensación de eficiencia es el disfraz del desperdicio.\n\nSe ve en escenas cotidianas. Escribes un informe mientras conversas por chat: cada mensaje entrante te saca del argumento, y al volver releés el último párrafo para recordar dónde ibas. Ese releer constante es el costo de la alternancia hecho visible. Al final, el informe tomó el doble y salió peor, y la conversación tampoco fue buena. La alternativa no es trabajar más horas: es trabajar en serie. Primero el informe con el chat cerrado, luego el chat con el informe cerrado. Mismas tareas, mismo tiempo disponible, resultados distintos: la monotarea es la forma más rápida de hacer dos cosas.\n\nEl matiz honesto: la monotarea incomoda al principio. Años de alternancia entrenaron al cerebro a esperar un estímulo nuevo cada pocos minutos, y cuando no llega, él mismo lo busca —de ahí el impulso de abrir otra pestaña "un segundo"—. Esa incomodidad no es señal de que la monotarea no funciona: es el síntoma de la abstinencia, y baja con la práctica. El error común es reservar la atención plena solo para lo laboral. Pruébala también en lo pequeño: comer sin pantalla, escuchar a alguien sin mirar el teléfono. La atención es un músculo general, y cada uso entrena al mismo.',
        apply: 'Elige ahora tu "única cosa" de hoy y trabájala antes de abrir el correo o la mensajería. Lo urgente puede esperar 25 minutos; lo importante no sobrevive al final del día.',
      },
      {
        id: 'costo-del-cambio-de-contexto',
        title: 'Cada cambio de contexto cobra peaje',
        idea: 'Revisar "solo un mensaje" no cuesta diez segundos: cuesta los quince o veinte minutos que tu cabeza tarda en volver a donde estaba. Es el residuo de atención: parte de tu mente se queda en la tarea anterior. Cinco interrupciones pequeñas pueden vaciar una mañana entera sin que nada parezca habérsela robado.',
        ideaLong:
          'Cuando saltas de una tarea a otra, tu atención no salta contigo: una parte se queda atrás, pensando en lo que dejaste. Es el residuo de atención, y explica por qué "revisar un mensaje" nunca cuesta lo que parece. El vistazo dura diez segundos, sí, pero al volver al informe tu mente trae el mensaje encima —qué respondo, qué habrá querido decir— y tarda varios minutos en recuperar la profundidad que tenía. La interrupción visible fue breve; la invisible sigue cobrando un rato largo. Y aquí está lo peor: el peaje se paga aunque no respondas. Ver la notificación basta para que el tema se instale de polizón en tu cabeza.\n\nHaz la cuenta de una mañana normal: cuatro horas de trabajo con un salto a mensajes, correo o redes cada veinte minutos son doce interrupciones. Si cada una deja varios minutos de residuo, la mañana entera transcurre en ese estado intermedio donde estás en todo y en nada, sin un solo tramo de profundidad real. Al mediodía llega la sensación familiar: estuve ocupado cuatro horas y no avancé en nada. Nadie te robó la mañana de un golpe; te la robaron en cuotas de veinte segundos.\n\nLa defensa no es la fuerza de voluntad sino la agrupación: junta lo interrumpible en momentos fijos. Mensajes y correo en tres ventanas al día —media mañana, después de almuerzo, antes de cerrar— y fuera de ellas, cerrados de verdad, no minimizados. Tres ventanas generosas cuestan menos que cuarenta vistazos, porque pagan tres peajes en lugar de cuarenta. El error común es creerse la excepción: "yo sí puedo alternar sin perder el hilo". La sensación de fluidez al alternar es real; la pérdida también, solo que no se siente. Por eso ayuda medirlo un día: las rayas en el papel no se engañan.',
        apply: 'Durante una hora de trabajo hoy, cuenta tus cambios de contexto: cada salto a otra app, pestaña o conversación, una raya en un papel. Solo medirlo ya cambia el comportamiento.',
        cta: { kind: 'habit', title: 'Revisar mensajes solo en 3 momentos del día', area: 'carrera' },
      },
      {
        id: 'decir-que-no',
        title: 'Decir que no es decir que sí',
        idea: 'Cada sí a algo pequeño es un no silencioso a tu trabajo importante: el tiempo no se estira. Decir que no no requiere excusas elaboradas; requiere claridad sobre qué estás protegiendo. Un "no puedo esta semana" amable y a tiempo es más respetuoso que un sí resentido que cumples a medias.',
        ideaLong:
          'El tiempo no se estira: cada compromiso nuevo se paga con horas que ya tenían dueño. Por eso todo sí es también un no, solo que invisible: dices sí a la reunión extra y, sin anunciarlo, le dices no a la hora de trabajo profundo, al gimnasio o a la cena sin prisa. El problema es que los síes se pronuncian y los noes implícitos no, así que nadie los ve, ni siquiera tú, hasta que el calendario amanece lleno y lo importante otra vez quedó afuera. La agenda saturada no llegó de golpe: se construyó con síes pequeños, uno por uno, cada uno razonable en su momento.\n\nDecir que no cuesta porque en el momento se siente como un costo social: no queremos decepcionar, quedar mal, cerrar puertas. Pero compara los dos caminos completos. El sí incómodo: aceptas por pena, lo arrastras dos semanas con resentimiento, lo cumples a medias y tarde, y quedas peor que si hubieras declinado. El no a tiempo: dos minutos incómodos, honestos y amables, y ambos siguen con su semana. Un "no puedo comprometerme con esto ahora" temprano es más respetuoso que un sí que se marchita. Y no necesita excusas elaboradas; las excusas invitan a negociar. Basta la verdad simple: esta semana estoy protegiendo un proyecto y no me cabe.\n\nEl matiz que lo cambia todo: el no funciona cuando sabes qué estás protegiendo. Sin una prioridad clara, cada pedido parece igual de válido y todo termina en sí; con ella, la decisión casi se toma sola —¿esto vale más que aquello?—. El error común es reservar el no para pedidos ajenos: tus propias ideas también piden calendario, y el proyecto nuevo que te entusiasma un martes puede ser el peor ladrón de la meta que empezaste hace un mes. A esos también se les dice "todavía no".',
        apply: 'Identifica un compromiso que aceptaste por inercia y renegócialo hoy: recórtalo, propón otra fecha o decláralo fuera de tu plato. Una conversación incómoda de dos minutos compra horas.',
      },
      {
        id: 'cerrar-el-dia',
        title: 'Cierra el día, abre el mañana',
        idea: 'El trabajo que termina "cuando ya no doy más" invade la noche y arranca mal el día siguiente. Un ritual de cierre cambia eso: revisas qué quedó abierto, decides la primera tarea de mañana y apagas. Así mañana no gastas tu mejor energía decidiendo por dónde empezar: ya lo decidió tu yo de hoy, que tenía el contexto fresco.',
        ideaLong:
          'Sin un cierre definido, el trabajo no termina: se disuelve. Apagas la laptop "cuando ya no das más", pero los pendientes sin resolver no se apagan contigo: la mente tiene una debilidad conocida por las tareas inconclusas y las mantiene activas, rondando, precisamente porque quedaron abiertas. Por eso el correo sin responder aparece en la ducha y el pendiente de mañana interrumpe la cena. No es que trabajes de noche: es que nunca dejaste de trabajar, solo bajaste la calidad a rumia de fondo. Y esa rumia arruina las dos puntas: la noche no descansa y la mañana arranca cargada.\n\nEl ritual de cierre resuelve el problema con diez minutos de estructura al final de la jornada. Tres pasos: revisa qué quedó abierto y anótalo donde confíes en encontrarlo —lo escrito con un cuándo deja de rondar, porque la cabeza ya no tiene que sostenerlo—; decide la primera tarea concreta de mañana, una sola, de esas que puedes empezar en cinco minutos; y ejecuta una señal física de fin —cerrar la laptop, ordenar el escritorio, una frase, salir a caminar—. La señal no es decorativa: es la frontera que le avisa al cerebro que el turno terminó y puede soltar.\n\nEl beneficio más subestimado aparece a la mañana siguiente. Tu primera hora es tu mejor energía, y sin cierre previo se gasta en la peor tarea posible: decidir por dónde empezar, que en la práctica significa "revisar el correo mientras decido", que significa perder la mañana. Con la primera tarea ya elegida desde ayer —por tu yo de la tarde, que tenía todo el contexto fresco—, arrancas ejecutando. El error común es saltarse el ritual justo los días caóticos, cuando más pendientes quedan abiertos. Esos días el cierre no es un lujo: es la diferencia entre una noche y una prórroga.',
        apply: 'Hoy, antes de cerrar la laptop, escribe la primera tarea concreta de mañana. Una sola, que puedas empezar en 5 minutos. Luego cierra de verdad.',
        cta: { kind: 'habit', title: 'Anotar la primera tarea de mañana al cerrar el día', area: 'carrera' },
      },
    ],
  },
  {
    id: 'constancia-sin-culpa',
    title: 'Constancia sin culpa',
    blurb: 'Sostener el ritmo sin castigarte cada vez que la vida se interpone.',
    area: 'bienestar',
    lessons: [
      {
        id: 'la-culpa-sabotea',
        title: 'La culpa no disciplina, frena',
        idea: 'Parece que sentirte mal por fallar te hará cumplir mañana, pero ocurre lo contrario: la culpa hace que evites pensar en el hábito, y lo que evitas no lo retomas. Quienes se perdonan tras un tropiezo vuelven antes que quienes se castigan. La culpa no es disciplina: es el impuesto que pagas por no volver.',
        ideaLong:
          'La teoría suena razonable: si fallar duele, mañana cumplirás para no volver a sentirlo. Por eso tanta gente se castiga con el discurso interno —"otra vez no fuiste, qué falta de disciplina"— convencida de que la dureza es exigencia. Pero el mecanismo real funciona al revés. La culpa vuelve doloroso pensar en el hábito, y el cerebro evita lo doloroso: dejas de abrir la app, esquivas el gimnasio hasta con la mirada, cambias de tema mental cada vez que aparece el asunto. Y un hábito en el que no puedes pensar es un hábito al que no puedes volver. La culpa no fortalece el compromiso: lo entierra bajo evitación.\n\nLa evidencia sobre autocompasión apunta en la misma dirección: quienes se tratan con amabilidad tras un tropiezo retoman antes y sostienen más que quienes se flagelan. Compara a dos personas que faltaron al gimnasio una semana. La primera se dice "soy un desastre": cada recuerdo del gimnasio le duele, así que lo piensa poco, y de esquive en esquive pasa un mes. La segunda se dice "fue una semana difícil; hoy toca versión corta": el gimnasio sigue siendo un lugar mentalmente habitable, y vuelve el lunes. Misma falla, dos futuros distintos, y la diferencia no fue la disciplina: fue el trato.\n\nEl matiz que evita el malentendido: autocompasión no es autoindulgencia. "No pasa nada, lo dejo para el próximo mes" es abandono con voz suave. La fórmula real tiene dos partes inseparables: cero drama sobre el pasado y acción mínima hoy. "No lo hice ayer. Hoy es otro día" —y la versión de dos minutos, ahora. El perdón sin acción es rendirse amablemente; el castigo sin perdón es rendirse a gritos. Volver sin drama es lo único que se parece a la disciplina.',
        apply: 'La próxima vez que falles, di una frase neutra: "No lo hice ayer. Hoy es otro día". Sin adjetivos sobre ti. Y luego haz la versión mínima del hábito.',
      },
      {
        id: 'imperfecto-pero-constante',
        title: 'Imperfecto y constante gana',
        idea: 'Diez minutos de ejercicio cuatro veces por semana construyen más que una sesión heroica de dos horas al mes. La perfección esporádica se siente épica pero no deja estructura; el progreso imperfecto se siente poca cosa pero se acumula. La pregunta correcta no es "¿lo hice perfecto?", sino "¿seguí en el juego?".',
        ideaLong:
          'Hay dos monedas en el progreso: la intensidad y la frecuencia, y elegimos mal casi siempre porque la intensidad se siente mejor. La sesión heroica —dos horas de gimnasio, un domingo entero de estudio— deja una sensación épica de haber hecho algo grande. Pero el cuerpo y el cerebro no mejoran durante los eventos: mejoran con la repetición espaciada. Diez minutos cuatro veces por semana le dan al sistema cuarenta señales al mes de "esto es lo que somos ahora"; la sesión heroica mensual le da una, y una señal aislada no construye adaptación ni identidad. La constancia mediocre le gana a la brillantez esporádica por goleada, solo que en cámara lenta.\n\nEl mecanismo detrás es la acumulación compuesta: cada repetición vale por sí misma y además abarata la siguiente, porque refuerza el circuito, la identidad y la logística del hábito. Doscientas palabras diarias parecen nada; en un año son un manuscrito. La espera del "fin de semana libre para escribir de verdad" también acumula, pero acumula cero, con intereses de frustración. Y hay un costo escondido en el modelo heroico: como cada sesión es enorme, cada sesión es negociable —hoy no tengo dos horas, mejor mañana— y el hábito vive de prórroga en prórroga.\n\nLa raíz del problema es el pensamiento de todo o nada: si no puedo hacerlo completo, no cuenta, entonces no lo hago. Esa regla convierte cada día imperfecto —que son la mayoría— en un cero, y los ceros no se acumulan. La alternativa es tener siempre una versión al 60% lista para los días reales: la caminata corta cuando no alcanza para el gimnasio, el borrador feo cuando no fluye la inspiración. El error común es despreciar esas versiones como "hacer trampa". Es al revés: son el seguro de vida del hábito. Lo que se hace a medias sobrevive; lo que exige perfección, no.',
        apply: 'Detecta dónde estás esperando condiciones perfectas (tiempo, energía, ánimo) y haz hoy la versión al 60%: la caminata corta, la sesión breve, el borrador feo.',
        cta: { kind: 'habit', title: 'Moverme 10 minutos al día', area: 'salud' },
      },
      {
        id: 'descanso-en-el-plan',
        title: 'El descanso es parte del plan',
        idea: 'Si descansar solo ocurre cuando colapsas, tu plan tiene un error de diseño. El descanso programado no es una pausa del progreso: es lo que lo hace sostenible, igual que dormir no es una pausa de estar vivo. Cuando el día libre está en el calendario, deja de ser una falla y se vuelve una pieza más del sistema.',
        ideaLong:
          'En el entrenamiento físico esto ya nadie lo discute: el músculo no crece durante la pesa, crece durante la recuperación. El estímulo sin descanso no produce mejora, produce lesión. Lo mental funciona igual —la concentración, la creatividad y la voluntad se recargan fuera del trabajo, no dentro— y sin embargo tratamos el descanso mental como un lujo culposo: algo que "nos permitimos" cuando ya no damos más. Ahí está el error de diseño: si el descanso solo llega por colapso, no es descanso, es avería. Y las averías no eligen buen momento.\n\nLa diferencia entre descansar por diseño y descansar por derrumbe es enorme aunque las horas sean las mismas. El descanso programado —el domingo libre en el calendario, la noche sin pendientes, la semana suave después de un mes intenso— llega antes del agotamiento, así que recarga de verdad; y como estaba en el plan, no genera culpa, y la culpa es justo lo que arruina el descanso: un domingo libre rumiando lo que "deberías" estar haciendo cansa más que trabajar. El descanso por derrumbe, en cambio, llega tarde, sabe a fracaso y suele venir acompañado del abandono del plan entero: "esto no es sostenible, lo dejo".\n\nDos matices prácticos. Primero, descanso no es cualquier no-trabajo: tres horas de scroll dejan la cabeza más cargada que antes; lo que recarga es lo que desconecta de verdad —caminar, cocinar, gente querida, dormir—. Segundo, el descanso se protege como una sesión: con día, con hora y sin negociarlo cuando aparece "algo importante", porque siempre aparece. El error común es verlo como el premio por terminar todo. Nunca se termina todo. El descanso no es lo que sobra al final del plan: es una de sus piezas, y de las que sostienen el resto.',
        apply: 'Decide hoy cuál es tu día o momento de descanso de la semana y trátalo con el mismo respeto que una sesión: no lo negocies ni lo llenes de pendientes.',
        cta: { kind: 'habit', title: 'Cerrar pantallas 30 min antes de dormir', area: 'bienestar' },
      },
      {
        id: 'volver-tras-una-pausa',
        title: 'Volver vale más que no parar',
        idea: 'Todo hábito de largo plazo incluye pausas: viajes, enfermedades, semanas imposibles. Lo que separa a quienes lo logran no es no parar nunca, sino volver rápido y sin drama. No intentes recuperar lo perdido en un día: eso convierte el regreso en castigo. Vuelve al nivel mínimo y sube desde ahí.',
        ideaLong:
          'Mira cualquier hábito sostenido durante años y encontrarás huecos: el viaje de trabajo, la gripe, la mudanza, el mes en que todo se juntó. Las pausas no son la excepción de los hábitos de largo plazo: son parte de su paisaje. Lo que distingue a quienes sostienen de quienes abandonan no es la ausencia de pausas —nadie la tiene— sino una sola variable: cuánto tardan en volver. Una pausa de dos semanas con regreso al día quince es una anécdota; la misma pausa con regreso "cuando me organice" es, casi siempre, el final. El costo real de una pausa no son los días perdidos: es la fricción de volver, que crece con cada día que pasa.\n\nY esa fricción tiene un amplificador conocido: la ambición del regreso. Quien vuelve al gimnasio tras un mes queriendo entrenar como antes de parar tiene dos finales posibles, y ambos malos: la sesión le resulta tan dura que confirma que "ya perdió todo", o la pospone precisamente porque sabe que será dura. En los dos casos, la exigencia convirtió el regreso en castigo, y a los castigos no se vuelve. La alternativa es humilde y funciona: la primera sesión de vuelta se hace en versión mínima, deliberadamente fácil, porque su objetivo no es rendir: es romper el hielo y reabrir la puerta. El nivel anterior se recupera después, y más rápido de lo que el pesimismo predice.\n\nEl matiz que previene el problema: los regresos se agendan, no se esperan. "Vuelvo cuando me sienta listo" es una fecha que no existe; "vuelvo el lunes, 10 minutos, después del café" sí. Si además sabes que viene una pausa —un viaje, una temporada cargada—, decide antes de irte el día y la versión mínima del regreso. Una pausa con fecha de regreso no es un abandono: es un paréntesis. Sin fecha, los paréntesis no se cierran solos.',
        apply: 'Si tienes un hábito en pausa, agenda hoy su regreso: día, hora y versión mínima. El objetivo de la primera sesión de vuelta no es rendir, es romper el hielo.',
        cta: { kind: 'goal', title: 'Retomar mi rutina de ejercicio', area: 'salud' },
      },
      {
        id: 'mide-lo-que-si-hiciste',
        title: 'Cuenta lo que sí hiciste',
        idea: 'Al final del día tu memoria registra el pendiente que faltó, no las cinco cosas que sí hiciste. Ese sesgo te hace sentir que nunca avanzas, aunque avances. Medir lo cumplido —no lo que faltó— corrige la imagen y alimenta la motivación con datos reales en lugar de impresiones.',
        ideaLong:
          'Tu memoria no es una cámara: es una editora con criterio propio, y su criterio favorece lo negativo. Es el sesgo de negatividad: lo que salió mal, lo que faltó y lo que amenaza pesa más en el recuerdo que lo que salió bien, porque durante casi toda la historia humana ignorar un peligro costaba más que ignorar una buena noticia. Útil para sobrevivir; pésimo para evaluar tu semana. Por eso el final del día tiene un guion tan predecible: hiciste cinco cosas y faltó una, y la que ocupa tu cabeza en la almohada es la que faltó. Cinco a uno en los hechos; uno a cinco en la sensación.\n\nEl problema no es solo anímico: esa sensación de "nunca avanzo" es información falsa, y tomas decisiones con ella. Gente que está progresando de verdad abandona metas porque su editora interna solo le muestra los huecos. La corrección es casi ridícula de simple: contar lo cumplido por escrito. Esta noche, tres cosas que sí hiciste, por pequeñas que sean —la sesión corta, el correo difícil que por fin salió, el no que lograste decir—. En papel o en notas del celular, da igual: lo que importa es sacar el recuento de la memoria sesgada y ponerlo donde los ojos puedan verificarlo. Contra una lista escrita, la sensación de día perdido pierde casi siempre.\n\nEl matiz para escépticos: esto no es optimismo decorativo ni autoengaño. El autoengaño sería inventar logros; esto es dejar de borrarlos. La lista no niega lo que faltó: le devuelve su tamaño real, una cosa entre seis, no la protagonista. Y con las semanas, el registro acumulado se vuelve un archivo de evidencia útil para los días grises: no "siento que avanzo", sino "aquí está escrito que avancé". El error común es hacerlo mentalmente. No funciona: el sesgo vive exactamente ahí. Escríbelo.',
        apply: 'Esta noche, antes de dormir, anota tres cosas que sí hiciste hoy, por pequeñas que sean. En papel o en notas: lo importante es verlas escritas.',
        cta: { kind: 'habit', title: 'Anotar 3 logros del día', area: 'bienestar' },
      },
    ],
  },
]
